fos_rest:
    view:
        view_response_listener: true
    body_listener:
        enabled: true
    format_listener:
        rules:
          - { host: api.exotest.fr, path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
          - { host: exotest.fr, path: ^/, priorities: [ html ] , fallback_format: html }